version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers 2 --bind 0.0.0.0:8000 image_web_classifier.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "8000:8000"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
