version: '3.8'

services:
  web:
    build: .
    container_name: image_web_classifier
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - .:/app
    command: gunicorn image_web_classifier.wsgi:application --bind 0.0.0.0:8000


