version: '3.8'

services:
  web:
    build: .
    container_name: image_web_classifier
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    command: python manage.py runserver 0.0.0.0:8000

