version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 image_web_classifier.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"

volumes:
  static_volume:
  media_volume:

