services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 image_web_classifier.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./main/static/main:/app/main/static/main
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:

